// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Model;

namespace UserService.Migrations
{
    [DbContext(typeof(RegistrationContext))]
    partial class RegistrationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserService.Model.Registration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<string>("forename");

                    b.Property<string>("password");

                    b.Property<string>("surename");

                    b.HasKey("id");

                    b.ToTable("_RegestrationDb");

                    b.HasData(
                        new { id = 1, email = "conor@version1.com", forename = "Conor", password = "conor123", surename = "ONeill" },
                        new { id = 2, email = "uncle.bob@gmail.com", forename = "Uncle", password = "bob123", surename = "Bob" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
